# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourapi', '0002_auto_20171124_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristfeedback',
            name='tourism_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourapi.TourismGuide'),
        ),
    ]
